[package]
name = "wizz"
version = "1.0.0"
authors = []

[addresses]
wizz_addr='7526d5a6bd74a678f27d302f71301c3cdea37f7d1149aae607b35e5d683cea94'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
