[package]
name = "wizz"
version = "1.0.0"
authors = []

[addresses]
wizz_addr='182a5965398f3af8b3daa8c664fb8e6ae3bc1b2a1ccce00a550b5ed94b23665b'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
