[package]
name = "wizz"
version = "1.0.0"
authors = []

[addresses]
wizz_addr='de756d9f7faba7bbccced3cd67392586def5b1efab311acc9be4d70e2b08212f'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
