[package]
name = "wizz"
version = "1.0.0"
authors = []

[addresses]
wizz_addr='8b275136d4a0d63000260b2c616b3e2f50b2386403d9dea2ee42cb1efa6b0ddb'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
